"""garment ai labels and classification feedback

Revision ID: 2063b16f0191
Revises: b298f121776d
Create Date: 2026-09-19 12:33:07.423212
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text  # noqa: F401 (used by JSONB astext_type)
import app.core.types  # noqa: F401 (custom GUID column type)
from sqlalchemy.dialects import postgresql

revision: str = '2063b16f0191'
down_revision: Union[str, None] = 'b298f121776d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classification_feedback',
    sa.Column('id', app.core.types.GUID(), nullable=False),
    sa.Column('garment_id', app.core.types.GUID(), nullable=True),
    sa.Column('user_id', app.core.types.GUID(), nullable=True),
    sa.Column('image_key', sa.String(length=512), nullable=False),
    sa.Column('field', sa.String(length=40), nullable=False),
    sa.Column('ai_value', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('user_value', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('ai_confidence', sa.Float(), nullable=False),
    sa.Column('backend', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['garment_id'], ['garments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('classification_feedback', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_classification_feedback_field'), ['field'], unique=False)
        batch_op.create_index(batch_op.f('ix_classification_feedback_garment_id'), ['garment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_classification_feedback_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('garments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ai_labels', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True))
        batch_op.add_column(sa.Column('classified_at', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('garments', schema=None) as batch_op:
        batch_op.drop_column('classified_at')
        batch_op.drop_column('ai_labels')

    with op.batch_alter_table('classification_feedback', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_classification_feedback_user_id'))
        batch_op.drop_index(batch_op.f('ix_classification_feedback_garment_id'))
        batch_op.drop_index(batch_op.f('ix_classification_feedback_field'))

    op.drop_table('classification_feedback')
    # ### end Alembic commands ###
