"""affiliate clicks

Revision ID: d33eae8774a2
Revises: c7f3feee9833
Create Date: 2026-09-20 01:21:49.128253
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text  # noqa: F401 (used by JSONB astext_type)
import app.core.types  # noqa: F401 (custom GUID column type)


revision: str = 'd33eae8774a2'
down_revision: Union[str, None] = 'c7f3feee9833'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('affiliate_clicks',
    sa.Column('id', app.core.types.GUID(), nullable=False),
    sa.Column('user_id', app.core.types.GUID(), nullable=True),
    sa.Column('garment_id', app.core.types.GUID(), nullable=True),
    sa.Column('gap_type', sa.String(length=50), nullable=True),
    sa.Column('platform', sa.Enum('myntra', 'ajio', 'nykaa', 'meesho', name='affiliate_platform', native_enum=False, length=20), nullable=False),
    sa.Column('product_url', sa.Text(), nullable=False),
    sa.Column('affiliate_url', sa.Text(), nullable=False),
    sa.Column('clicked_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('converted', sa.Boolean(), nullable=False),
    sa.Column('converted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('order_value_inr', sa.Integer(), nullable=True),
    sa.Column('commission_inr', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['garment_id'], ['garments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('affiliate_clicks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_affiliate_clicks_platform'), ['platform'], unique=False)
        batch_op.create_index(batch_op.f('ix_affiliate_clicks_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('affiliate_clicks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_affiliate_clicks_user_id'))
        batch_op.drop_index(batch_op.f('ix_affiliate_clicks_platform'))

    op.drop_table('affiliate_clicks')
    # ### end Alembic commands ###
