"""social sharing

Revision ID: a14ad26e1832
Revises: 79994ca3d25b
Create Date: 2026-09-20 02:01:04.156800
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text  # noqa: F401 (used by JSONB astext_type)
import app.core.types  # noqa: F401 (custom GUID column type)


revision: str = 'a14ad26e1832'
down_revision: Union[str, None] = '79994ca3d25b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('outfit_likes',
    sa.Column('id', app.core.types.GUID(), nullable=False),
    sa.Column('outfit_id', app.core.types.GUID(), nullable=False),
    sa.Column('user_id', app.core.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['outfit_id'], ['outfits.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('outfit_id', 'user_id', name='uq_outfit_like')
    )
    with op.batch_alter_table('outfit_likes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_outfit_likes_outfit_id'), ['outfit_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_outfit_likes_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('outfits', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_public', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.add_column(sa.Column('shared_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('share_slug', sa.String(length=16), nullable=True))
        batch_op.add_column(sa.Column('share_card_key', sa.String(length=512), nullable=True))
        batch_op.add_column(sa.Column('like_count', sa.Integer(), nullable=False, server_default='0'))
        batch_op.create_index(batch_op.f('ix_outfits_share_slug'), ['share_slug'], unique=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('social_sharing_enabled', sa.Boolean(), nullable=False, server_default=sa.false()))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('social_sharing_enabled')

    with op.batch_alter_table('outfits', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_outfits_share_slug'))
        batch_op.drop_column('like_count')
        batch_op.drop_column('share_card_key')
        batch_op.drop_column('share_slug')
        batch_op.drop_column('shared_at')
        batch_op.drop_column('is_public')

    with op.batch_alter_table('outfit_likes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_outfit_likes_user_id'))
        batch_op.drop_index(batch_op.f('ix_outfit_likes_outfit_id'))

    op.drop_table('outfit_likes')
    # ### end Alembic commands ###
