"""brand campaigns

Revision ID: b146a692e71e
Revises: c055480640d6
Create Date: 2026-09-20 12:39:18.406925
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text  # noqa: F401 (used by JSONB astext_type)
import app.core.types  # noqa: F401 (custom GUID column type)
from sqlalchemy.dialects import postgresql

revision: str = 'b146a692e71e'
down_revision: Union[str, None] = 'c055480640d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaign_entries',
    sa.Column('id', app.core.types.GUID(), nullable=False),
    sa.Column('campaign_id', app.core.types.GUID(), nullable=False),
    sa.Column('user_id', app.core.types.GUID(), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('outfit_ids', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['brand_campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('campaign_id', 'user_id', name='uq_campaign_entry')
    )
    with op.batch_alter_table('campaign_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_campaign_entries_campaign_id'), ['campaign_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_campaign_entries_user_id'), ['user_id'], unique=False)

    op.create_table('campaign_events',
    sa.Column('id', app.core.types.GUID(), nullable=False),
    sa.Column('campaign_id', app.core.types.GUID(), nullable=False),
    sa.Column('user_id', app.core.types.GUID(), nullable=True),
    sa.Column('event', sa.Enum('view', 'join', 'submit', 'complete', 'click', name='campaign_event_type', native_enum=False, length=20), nullable=False),
    sa.Column('meta', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['brand_campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('campaign_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_campaign_events_campaign_id'), ['campaign_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_campaign_events_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_campaign_events_event'), ['event'], unique=False)
        batch_op.create_index(batch_op.f('ix_campaign_events_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('brand_partners', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tagline', sa.String(length=160), nullable=True))
        batch_op.add_column(sa.Column('logo_url', sa.Text(), nullable=True))

    with op.batch_alter_table('garments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('brand', sa.String(length=80), nullable=True))
        batch_op.create_index(batch_op.f('ix_garments_brand'), ['brand'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('garments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_garments_brand'))
        batch_op.drop_column('brand')

    with op.batch_alter_table('brand_partners', schema=None) as batch_op:
        batch_op.drop_column('logo_url')
        batch_op.drop_column('tagline')

    with op.batch_alter_table('campaign_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_campaign_events_user_id'))
        batch_op.drop_index(batch_op.f('ix_campaign_events_event'))
        batch_op.drop_index(batch_op.f('ix_campaign_events_created_at'))
        batch_op.drop_index(batch_op.f('ix_campaign_events_campaign_id'))

    op.drop_table('campaign_events')
    with op.batch_alter_table('campaign_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_campaign_entries_user_id'))
        batch_op.drop_index(batch_op.f('ix_campaign_entries_campaign_id'))

    op.drop_table('campaign_entries')
    # ### end Alembic commands ###
