"""spec conformance: rating, notification prefs, festival overrides, payouts, brand fields

Revision ID: 45b8ec3c629c
Revises: 0cf608310f63
Create Date: 2026-09-20 17:37:12.960782
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text  # noqa: F401 (used by JSONB astext_type)
import app.core.types  # noqa: F401 (custom GUID column type)
from sqlalchemy.dialects import postgresql

revision: str = '45b8ec3c629c'
down_revision: Union[str, None] = '0cf608310f63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('festival_date_overrides',
    sa.Column('id', app.core.types.GUID(), nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug', 'year', name='uq_festival_year')
    )
    with op.batch_alter_table('festival_date_overrides', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_festival_date_overrides_slug'), ['slug'], unique=False)

    with op.batch_alter_table('brand_partners', schema=None) as batch_op:
        batch_op.add_column(sa.Column('affiliate_id', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('categories', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True))

    with op.batch_alter_table('outfits', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rating', sa.Integer(), nullable=True))

    with op.batch_alter_table('stylist_bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payout_status', sa.String(length=10), nullable=False, server_default='none'))
        batch_op.add_column(sa.Column('payout_paid_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('payout_ref', sa.String(length=80), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notification_prefs', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('notification_prefs')

    with op.batch_alter_table('stylist_bookings', schema=None) as batch_op:
        batch_op.drop_column('payout_ref')
        batch_op.drop_column('payout_paid_at')
        batch_op.drop_column('payout_status')

    with op.batch_alter_table('outfits', schema=None) as batch_op:
        batch_op.drop_column('rating')

    with op.batch_alter_table('brand_partners', schema=None) as batch_op:
        batch_op.drop_column('categories')
        batch_op.drop_column('affiliate_id')

    with op.batch_alter_table('festival_date_overrides', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_festival_date_overrides_slug'))

    op.drop_table('festival_date_overrides')
    # ### end Alembic commands ###
