"""outfit engine fields

Revision ID: 706fa2a2c782
Revises: 2063b16f0191
Create Date: 2026-09-19 12:45:26.398503
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text  # noqa: F401 (used by JSONB astext_type)
import app.core.types  # noqa: F401 (custom GUID column type)
from sqlalchemy.dialects import postgresql

revision: str = '706fa2a2c782'
down_revision: Union[str, None] = '2063b16f0191'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('outfits', schema=None) as batch_op:
        batch_op.add_column(sa.Column('season', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('weather_source', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('batch_id', app.core.types.GUID(), nullable=True))
        batch_op.add_column(sa.Column('score', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('rationale', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False))
        batch_op.add_column(sa.Column('for_date', sa.String(length=10), nullable=True))
        batch_op.create_index(batch_op.f('ix_outfits_batch_id'), ['batch_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('outfits', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_outfits_batch_id'))
        batch_op.drop_column('for_date')
        batch_op.drop_column('rationale')
        batch_op.drop_column('score')
        batch_op.drop_column('batch_id')
        batch_op.drop_column('weather_source')
        batch_op.drop_column('season')

    # ### end Alembic commands ###
