"""brand partners scaffold

Revision ID: 79994ca3d25b
Revises: 34eabc843446
Create Date: 2026-09-20 01:46:52.867421
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text  # noqa: F401 (used by JSONB astext_type)
import app.core.types  # noqa: F401 (custom GUID column type)
from sqlalchemy.dialects import postgresql

revision: str = '79994ca3d25b'
down_revision: Union[str, None] = '34eabc843446'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brand_partners',
    sa.Column('id', app.core.types.GUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('status', sa.Enum('prospect', 'active', 'paused', name='brand_status', native_enum=False, length=20), nullable=False),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('brand_partners', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_brand_partners_slug'), ['slug'], unique=True)

    op.create_table('brand_campaigns',
    sa.Column('id', app.core.types.GUID(), nullable=False),
    sa.Column('brand_id', app.core.types.GUID(), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('config', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brand_partners.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('brand_campaigns', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_brand_campaigns_brand_id'), ['brand_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('brand_campaigns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_brand_campaigns_brand_id'))

    op.drop_table('brand_campaigns')
    with op.batch_alter_table('brand_partners', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_brand_partners_slug'))

    op.drop_table('brand_partners')
    # ### end Alembic commands ###
