"""notification log

Revision ID: ac8f5cc037b6
Revises: 706fa2a2c782
Create Date: 2026-09-19 12:58:42.310038
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text  # noqa: F401 (used by JSONB astext_type)
import app.core.types  # noqa: F401 (custom GUID column type)


revision: str = 'ac8f5cc037b6'
down_revision: Union[str, None] = '706fa2a2c782'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_log',
    sa.Column('id', app.core.types.GUID(), nullable=False),
    sa.Column('user_id', app.core.types.GUID(), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('key', sa.String(length=120), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'kind', 'key', name='uq_notification_once')
    )
    with op.batch_alter_table('notification_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notification_log_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notification_log_user_id'))

    op.drop_table('notification_log')
    # ### end Alembic commands ###
