"""garment care tracking

Revision ID: 34eabc843446
Revises: d33eae8774a2
Create Date: 2026-09-20 01:27:43.093187
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text  # noqa: F401 (used by JSONB astext_type)
import app.core.types  # noqa: F401 (custom GUID column type)


revision: str = '34eabc843446'
down_revision: Union[str, None] = 'd33eae8774a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('garments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('wears_since_care', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('last_cared_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('care_reminders_enabled', sa.Boolean(), nullable=False, server_default=sa.true()))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('garments', schema=None) as batch_op:
        batch_op.drop_column('care_reminders_enabled')
        batch_op.drop_column('last_cared_at')
        batch_op.drop_column('wears_since_care')

    # ### end Alembic commands ###
