"""stylist marketplace

Revision ID: 8650b05784cb
Revises: a14ad26e1832
Create Date: 2026-09-20 02:08:41.114744
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text  # noqa: F401 (used by JSONB astext_type)
import app.core.types  # noqa: F401 (custom GUID column type)
from sqlalchemy.dialects import postgresql

revision: str = '8650b05784cb'
down_revision: Union[str, None] = 'a14ad26e1832'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stylist_bookings',
    sa.Column('id', app.core.types.GUID(), nullable=False),
    sa.Column('user_id', app.core.types.GUID(), nullable=False),
    sa.Column('stylist_id', app.core.types.GUID(), nullable=False),
    sa.Column('session_type', sa.Enum('wardrobe_review', 'occasion_curation', 'trip_packing', name='session_type', native_enum=False, length=20), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'confirmed', 'completed', 'cancelled', name='booking_status', native_enum=False, length=20), nullable=False),
    sa.Column('amount_paid', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('platform_commission', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('discount_inr', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('payment_provider', sa.String(length=20), nullable=True),
    sa.Column('payment_ref', sa.String(length=80), nullable=True),
    sa.Column('payment_url', sa.Text(), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['stylist_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stylist_bookings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stylist_bookings_payment_ref'), ['payment_ref'], unique=False)
        batch_op.create_index(batch_op.f('ix_stylist_bookings_stylist_id'), ['stylist_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stylist_bookings_user_id'), ['user_id'], unique=False)

    op.create_table('stylist_reviews',
    sa.Column('id', app.core.types.GUID(), nullable=False),
    sa.Column('booking_id', app.core.types.GUID(), nullable=False),
    sa.Column('stylist_id', app.core.types.GUID(), nullable=False),
    sa.Column('user_id', app.core.types.GUID(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['stylist_bookings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['stylist_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('booking_id', name='uq_review_per_booking')
    )
    with op.batch_alter_table('stylist_reviews', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stylist_reviews_stylist_id'), ['stylist_id'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_stylist', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.add_column(sa.Column('stylist_verified', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.add_column(sa.Column('stylist_bio', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('stylist_specialties', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True))
        batch_op.add_column(sa.Column('stylist_price_per_session', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('stylist_portfolio_urls', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True))
        batch_op.add_column(sa.Column('stylist_applied_at', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('stylist_applied_at')
        batch_op.drop_column('stylist_portfolio_urls')
        batch_op.drop_column('stylist_price_per_session')
        batch_op.drop_column('stylist_specialties')
        batch_op.drop_column('stylist_bio')
        batch_op.drop_column('stylist_verified')
        batch_op.drop_column('is_stylist')

    with op.batch_alter_table('stylist_reviews', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stylist_reviews_stylist_id'))

    op.drop_table('stylist_reviews')
    with op.batch_alter_table('stylist_bookings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stylist_bookings_user_id'))
        batch_op.drop_index(batch_op.f('ix_stylist_bookings_stylist_id'))
        batch_op.drop_index(batch_op.f('ix_stylist_bookings_payment_ref'))

    op.drop_table('stylist_bookings')
    # ### end Alembic commands ###
