"""initial schema

Revision ID: b298f121776d
Revises: 
Create Date: 2026-09-19 11:52:53.849819
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text  # noqa: F401 (used by JSONB astext_type)
import app.core.types  # noqa: F401 (custom GUID column type)
from sqlalchemy.dialects import postgresql

revision: str = 'b298f121776d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('festivals',
    sa.Column('id', app.core.types.GUID(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('date_this_year', sa.Date(), nullable=False),
    sa.Column('region', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('color_codes', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('dress_code', sa.Text(), nullable=False),
    sa.Column('occasion_tags', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('festivals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_festivals_slug'), ['slug'], unique=True)

    op.create_table('otp_codes',
    sa.Column('id', app.core.types.GUID(), nullable=False),
    sa.Column('phone', sa.String(length=16), nullable=False),
    sa.Column('code_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('consumed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('otp_codes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_otp_codes_phone'), ['phone'], unique=False)

    op.create_table('users',
    sa.Column('id', app.core.types.GUID(), nullable=False),
    sa.Column('phone', sa.String(length=16), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('city', sa.String(length=80), nullable=False),
    sa.Column('gender', sa.Enum('female', 'male', 'other', name='gender', native_enum=False, length=20), nullable=False),
    sa.Column('body_type', sa.Enum('petite', 'regular', 'tall', 'plus', name='body_type', native_enum=False, length=20), nullable=False),
    sa.Column('skin_tone', sa.Enum('fair', 'wheatish', 'medium', 'dark', name='skin_tone', native_enum=False, length=20), nullable=False),
    sa.Column('regional_style', sa.String(length=50), nullable=False),
    sa.Column('subscription_tier', sa.Enum('free', 'plus', 'pro', name='subscription_tier', native_enum=False, length=20), nullable=False),
    sa.Column('subscription_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fcm_token', sa.String(length=512), nullable=True),
    sa.Column('onboarding_complete', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_phone'), ['phone'], unique=True)

    op.create_table('garments',
    sa.Column('id', app.core.types.GUID(), nullable=False),
    sa.Column('user_id', app.core.types.GUID(), nullable=False),
    sa.Column('image_key', sa.String(length=512), nullable=False),
    sa.Column('thumbnail_key', sa.String(length=512), nullable=True),
    sa.Column('garment_type', sa.String(length=50), nullable=False),
    sa.Column('fabric_type', sa.String(length=50), nullable=False),
    sa.Column('color_primary', sa.String(length=30), nullable=False),
    sa.Column('color_accent', sa.String(length=30), nullable=True),
    sa.Column('occasion_tags', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('season_tags', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('regional_style', sa.String(length=50), nullable=True),
    sa.Column('ai_confidence', sa.Float(), nullable=False),
    sa.Column('classification_status', sa.Enum('pending', 'complete', 'failed', name='classification_status', native_enum=False, length=20), nullable=False),
    sa.Column('user_verified', sa.Boolean(), nullable=False),
    sa.Column('care_profile', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('purchase_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('purchase_date', sa.Date(), nullable=True),
    sa.Column('condition', sa.Enum('new', 'good', 'worn', name='garment_condition', native_enum=False, length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('wear_count', sa.Integer(), nullable=False),
    sa.Column('last_worn_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('garments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_garments_user_id'), ['user_id'], unique=False)

    op.create_table('outfits',
    sa.Column('id', app.core.types.GUID(), nullable=False),
    sa.Column('user_id', app.core.types.GUID(), nullable=False),
    sa.Column('garment_ids', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('occasion', sa.String(length=50), nullable=False),
    sa.Column('weather_condition', sa.String(length=50), nullable=False),
    sa.Column('temperature_celsius', sa.Integer(), nullable=False),
    sa.Column('festival', sa.String(length=50), nullable=True),
    sa.Column('is_daily', sa.Boolean(), nullable=False),
    sa.Column('is_saved', sa.Boolean(), nullable=False),
    sa.Column('feedback', sa.Integer(), nullable=True),
    sa.Column('worn_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('outfits', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_outfits_user_id'), ['user_id'], unique=False)

    op.create_table('refresh_tokens',
    sa.Column('id', app.core.types.GUID(), nullable=False),
    sa.Column('user_id', app.core.types.GUID(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_refresh_tokens_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_user_id'))

    op.drop_table('refresh_tokens')
    with op.batch_alter_table('outfits', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_outfits_user_id'))

    op.drop_table('outfits')
    with op.batch_alter_table('garments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_garments_user_id'))

    op.drop_table('garments')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_phone'))

    op.drop_table('users')
    with op.batch_alter_table('otp_codes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_otp_codes_phone'))

    op.drop_table('otp_codes')
    with op.batch_alter_table('festivals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_festivals_slug'))

    op.drop_table('festivals')
    # ### end Alembic commands ###
