"""subscriptions and billing events

Revision ID: c7f3feee9833
Revises: 92e395bbc90b
Create Date: 2026-09-19 20:08:38.068946
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text  # noqa: F401 (used by JSONB astext_type)
import app.core.types  # noqa: F401 (custom GUID column type)
from sqlalchemy.dialects import postgresql

revision: str = 'c7f3feee9833'
down_revision: Union[str, None] = '92e395bbc90b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('billing_events',
    sa.Column('id', app.core.types.GUID(), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('provider_event_id', sa.String(length=120), nullable=False),
    sa.Column('event_type', sa.String(length=60), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_event_id', name='uq_billing_event')
    )
    op.create_table('subscriptions',
    sa.Column('id', app.core.types.GUID(), nullable=False),
    sa.Column('user_id', app.core.types.GUID(), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('provider_subscription_id', sa.String(length=80), nullable=False),
    sa.Column('plan', sa.String(length=10), nullable=False),
    sa.Column('status', sa.Enum('created', 'active', 'cancelled', 'halted', 'expired', name='subscription_status', native_enum=False, length=20), nullable=False),
    sa.Column('checkout_url', sa.Text(), nullable=True),
    sa.Column('current_period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancel_at_period_end', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_subscription_id')
    )
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subscriptions_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subscriptions_user_id'))

    op.drop_table('subscriptions')
    op.drop_table('billing_events')
    # ### end Alembic commands ###
